### ISSUE TITLE
Usage prompt is inaccurate

### ISSUE THREAD

**Issue by andylin2004** [joshluongo/frameme#4]
If I open up my terminal session and type in frameme (assuming that I placed the command line tool into the appropriate place), it will give me the usage prompt of using frame-me, when the command line tool is named frameme.
<img width="682" alt="Screenshot 2023-05-23 at 1 21 56 PM" src="https://github.com/joshluongo/frameme/assets/60021592/f8669063-0722-4545-8104-b73c798e4986">

**Comment by joshluongo** [comment]
Good catch! It happened from the ArgumentParser framework converting the main class name.
